/*
   Copyright 2021 Hiroshi.tao

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package lib

import (
	"bytes"
	"text/template"

	"pkg.tcw.im/rtfd/v2/pkg/util"
)

// caddySite Caddy 站点块：一组域名共用一个文档根目录
type caddySite struct {
	// Address 站点地址列表（半角逗号分隔的域名，如 "a.example.com, docs.custom.com"）
	Address string
	// Root 该站点的文档根目录
	Root string
	// Redirect 非空时生成 `redir / <Redirect> 302`（默认语言 latest 固定跳转）
	Redirect string
}

// caddyOptions 渲染 Caddy 单实例配置（Caddyfile）所需参数：
// 汇总全部文档项目为多个站点块，站点证书由 Caddy 自动申请与续期
type caddyOptions struct {
	Now   string      // 生成时间
	Email string      // ACME 账户邮箱（可选）
	Sites []caddySite // 站点块

	StaticExpires string // 静态资源缓存秒数，空表示不设置缓存头
	HTMLNoCache   bool   // html 是否禁用强缓存（改用 no-cache 协商缓存）
}

// caddyAddress 拼装 Caddy 站点地址：autoHTTPS 为 false 时加 `http://` 前缀，
// 表示该站点不启用自动 HTTPS（Caddy 仅以 HTTP 提供服务，不申请证书），适用于内网/开发环境。
func caddyAddress(domain string, autoHTTPS bool) string {
	if autoHTTPS {
		return domain
	}
	return "http://" + domain
}

// render 渲染 Caddy 单实例 Caddyfile 配置
func (opt *caddyOptions) render() (conf string, err error) {
	if opt.Now == "" {
		opt.Now = util.GetNow()
	}
	tmpl, err := template.New("caddy").Parse(caddyTPL())
	if err != nil {
		return
	}

	var result bytes.Buffer
	err = tmpl.Execute(&result, opt)
	if err != nil {
		return
	}
	return result.String(), nil
}

func caddyTPL() string {
	return `#: Automatic generated by rtfd at {{ .Now }}
#: 汇总全部文档项目的 Caddy 配置，请勿手工编辑；各站点证书由 Caddy 自动申请与续期
{{ if .Email }}{
	email {{ .Email }}
}
{{ end }}{{ range .Sites }}{{ .Address }} {
	root * {{ .Root }}
	encode gzip zstd
{{ if $.StaticExpires }}	#: 静态资源（Sphinx 的 _static/_images 及 css/js/图片/字体等）可安全强缓存
	@static path /_static/* /_images/* /_downloads/* *.css *.js *.png *.jpg *.jpeg *.gif *.ico *.svg *.woff *.woff2 *.ttf *.eot
	header @static Cache-Control "public, max-age={{ $.StaticExpires }}"
{{ end }}{{ if $.HTMLNoCache }}	#: 文档内容会随重建变化，html 使用协商缓存（可 304，不复用过期副本）
	@html path *.html
	header @html Cache-Control "no-cache"
{{ end }}{{ if .Redirect }}	#: 默认语言 latest 固定跳转
	redir / {{ .Redirect }} 302
{{ end }}	file_server
}

{{ end }}`
}
