/*
   Copyright 2021 Hiroshi.tao

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package lib

import (
	"bytes"
	"errors"
	"text/template"

	"pkg.tcw.im/rtfd/v2/pkg/util"

	"pkg.tcw.im/gtc"
)

// 渲染nginx配置文件所需参数，前四项是必填项，后面选填，最后Now、SSL、SSLCFG会自动填充
type nginxOptions struct {
	Name    string // 文档项目名
	Lang    string // 文档默认语言
	Domain  string // 默认域名或自定义域名
	DocsDir string // 文档项目所在的父目录

	Single bool   // 单一版本
	SSLCrt string // ssl公钥
	SSLKey string // ssl私钥

	StaticExpires string // 静态资源缓存时间（秒），空表示不设置缓存头
	HTMLNoCache   bool   // html是否禁用强缓存（改用no-cache协商缓存）
	OpenFileCache bool   // 是否开启文件元数据缓存

	Now    string // 当前时间
	SSL    bool   // 是否开启ssl
	SSLCFG string // ssl配置内容
}

func (opt *nginxOptions) render() (conf string, err error) {
	if opt.Name == "" || opt.Lang == "" || opt.Domain == "" || opt.DocsDir == "" {
		err = errors.New("found empty field")
		return
	}
	if opt.Now == "" {
		opt.Now = util.GetNow()
	}
	if gtc.IsFile(opt.SSLCrt) && gtc.IsFile(opt.SSLKey) {
		ssltpl, e := template.New("ssl").Parse(nginxSSLTPL())
		if e != nil {
			err = e
			return
		}
		var sslcfg bytes.Buffer
		e = ssltpl.Execute(&sslcfg, struct{ SSLCrt, SSLKey string }{opt.SSLCrt, opt.SSLKey})
		if e != nil {
			err = e
			return
		}
		opt.SSL = true
		opt.SSLCFG = sslcfg.String()
	} else {
		opt.SSL = false
	}

	var tpl string
	if opt.Single {
		tpl = nginxSingleTPL()
	} else {
		tpl = nginxMultiTPL()
	}
	tmpl, err := template.New("nginx").Parse(tpl)
	if err != nil {
		return
	}

	var result bytes.Buffer
	err = tmpl.Execute(&result, opt)
	if err != nil {
		return
	}
	return result.String(), nil
}

func nginxMultiTPL() string {
	// 通用模板，需要参数：
	return `#: Automatic generated by rtfd at {{ .Now }}
server {
    listen 80;
    {{- if .SSL }}
    listen 443 ssl http2;
    {{- end }}
    server_name {{ .Domain }};
    charset utf-8;
    root {{ .DocsDir }}/{{ .Name }}/;
    index index.html master.html;
    set $home /{{ .Lang }}/latest;
    error_page 403 =404 /404.html;
    {{- if .SSL }}
    {{ .SSLCFG }}
    {{- end }}
    {{- if .OpenFileCache }}
    #: 缓存文件元数据，降低大量静态文档的 stat/open 开销
    open_file_cache max=5000 inactive=30s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
    {{- end }}
    #: 静态资源（Sphinx的_static、_images及常见静态后缀）可安全缓存
    location ~* ^/(_static|_images|_downloads)/|\.(css|js|png|jpe?g|gif|ico|svg|woff2?|ttf|eot)$ {
        {{- if .StaticExpires }}
        expires {{ .StaticExpires }}s;
        add_header Cache-Control "public";
        {{- end }}
        access_log off;
    }
    location / {
        {{- if .HTMLNoCache }}
        #: 文档内容会随重建变化，html使用协商缓存（可304，不复用过期副本）
        add_header Cache-Control "no-cache";
        {{- end }}
        if (-e $document_root$home$document_uri) {
            return 302 $home$document_uri$is_args$args;
        }
    }
}
`
}

func nginxSingleTPL() string {
	// 单一版本的模板，参数要求同通用模板
	return `#: Automatic generated by rtfd at {{ .Now }}
server {
    listen 80;
    {{- if .SSL }}
    listen 443 ssl http2;
    {{- end }}
    server_name {{ .Domain }};
    charset utf-8;
    root {{ .DocsDir }}/{{ .Name }}/{{ .Lang }}/latest/;
    index index.html master.html;
    {{- if .SSL }}
    {{ .SSLCFG }}
    {{- end }}
    {{- if .OpenFileCache }}
    #: 缓存文件元数据，降低大量静态文档的 stat/open 开销
    open_file_cache max=5000 inactive=30s;
    open_file_cache_valid 30s;
    open_file_cache_min_uses 2;
    open_file_cache_errors on;
    {{- end }}
    #: 静态资源（Sphinx的_static、_images及常见静态后缀）可安全缓存
    location ~* ^/(_static|_images|_downloads)/|\.(css|js|png|jpe?g|gif|ico|svg|woff2?|ttf|eot)$ {
        {{- if .StaticExpires }}
        expires {{ .StaticExpires }}s;
        add_header Cache-Control "public";
        {{- end }}
        access_log off;
    }
    {{- if .HTMLNoCache }}
    #: 文档内容会随重建变化，html使用协商缓存（可304，不复用过期副本）
    location ~* \.html$ {
        add_header Cache-Control "no-cache";
    }
    {{- end }}
}
`
}

func nginxSSLTPL() string {
	// SSL 片段：由主模板在 {{ .SSLCFG }} 处插入 server 块内，需传入证书(SSLCrt)、私钥(SSLKey)。
	// 已做现代安全加固：禁用 TLS1.0/1.1、采用前向安全加密套件、共享会话缓存、HSTS。
	return `#: http 强制跳转 https
    if ($scheme = http) {
        return 301 https://$server_name$request_uri;
    }
    #: 证书与私钥
    ssl_certificate {{ .SSLCrt }};
    ssl_certificate_key {{ .SSLKey }};
    #: OCSP 装订（verify 需 ssl_trusted_certificate 指向 CA 链）
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 114.114.114.114 valid=300s;
    resolver_timeout 5s;
    #: 会话复用：多 worker 共享缓存，优于默认 session tickets
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    #: 仅启用 TLS1.2/1.3，禁用已废弃且不安全的 TLS1.0/1.1
    ssl_protocols TLSv1.2 TLSv1.3;
    #: 现代加密套件（ECDHE 前向安全，已移除 3DES/RC4 等弱套件）
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;
    #: HSTS（含 preload，按需要调整 max-age）
    add_header Strict-Transport-Security "max-age=31536000;preload";
    `
}
