/*
   Copyright 2021 Hiroshi.tao

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/

package lib

import (
	"bytes"
	"text/template"

	"pkg.tcw.im/rtfd/v2/pkg/util"
)

// swsVHost SWS 虚拟主机：按 Host 头分发到对应文档根目录
type swsVHost struct {
	Host string // 域名
	Root string // 该域名的文档根目录
}

// swsRedirect SWS 重定向：按 Host 限定的默认语言 latest 固定跳转
type swsRedirect struct {
	Host        string // 域名，空表示不限
	Source      string // 匹配的请求路径（glob）
	Destination string // 跳转目标
	Kind        int    // HTTP 状态码
}

// swsOptions 渲染 SWS（static-web-server）单实例配置所需参数：
// 汇总全部文档项目为一个虚拟主机列表，另加全局的监听、TLS、缓存与跳转设置
type swsOptions struct {
	Now  string // 生成时间
	Host string // 监听地址
	Port uint   // 监听端口
	Root string // 默认根目录（未命中虚拟主机时使用）

	VHosts    []swsVHost    // 虚拟主机（host -> root）
	Redirects []swsRedirect // 固定跳转（按 host 限定）

	TLSCert string // TLS 证书，空表示不启用 HTTPS
	TLSKey  string // TLS 私钥

	StaticExpires string // 静态资源缓存秒数，空表示不设置缓存头
	HTMLNoCache   bool   // html 是否禁用强缓存（改用 no-cache 协商缓存）
}

// render 渲染 SWS 单实例 TOML 配置
func (opt *swsOptions) render() (conf string, err error) {
	if opt.Now == "" {
		opt.Now = util.GetNow()
	}
	if opt.Host == "" {
		opt.Host = "0.0.0.0"
	}
	if opt.Port == 0 {
		opt.Port = 80
	}
	tmpl, err := template.New("sws").Parse(swsTPL())
	if err != nil {
		return
	}

	var result bytes.Buffer
	err = tmpl.Execute(&result, opt)
	if err != nil {
		return
	}
	return result.String(), nil
}

func swsTPL() string {
	return `#: Automatic generated by rtfd at {{ .Now }}
#: 汇总全部文档项目的 static-web-server 单实例配置，请勿手工编辑
[general]
host = "{{ .Host }}"
port = {{ .Port }}
root = "{{ .Root }}"
{{ if .TLSCert }}#: 启用 HTTPS（单证书，全部域名共用）
http2 = true
http2-tls-cert = "{{ .TLSCert }}"
http2-tls-key = "{{ .TLSKey }}"
https-redirect = true
{{ end }}{{ if .StaticExpires }}#: 静态资源（Sphinx 的 _static/_images 及 css/js/图片/字体等）可安全强缓存
[[advanced.headers]]
source = "**/*.{css,js,png,jpg,jpeg,gif,ico,svg,woff,woff2,ttf,eot}"
headers = { Cache-Control = "public, max-age={{ .StaticExpires }}" }
{{ end }}{{ if .HTMLNoCache }}#: 文档内容会随重建变化，html 使用协商缓存（可 304，不复用过期副本）
[[advanced.headers]]
source = "**/*.html"
headers = { Cache-Control = "no-cache" }
{{ end }}{{ range .Redirects }}#: 默认语言 latest 固定跳转
[[advanced.redirects]]
host = "{{ .Host }}"
source = "{{ .Source }}"
destination = "{{ .Destination }}"
kind = {{ .Kind }}
{{ end }}{{ range .VHosts }}[[advanced.virtual-hosts]]
host = "{{ .Host }}"
root = "{{ .Root }}"
{{ end }}`
}
