project_name: rtfd
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X pkg/tcw.im/rtfd/cmd.built={{.Date}}
      - -X pkg/tcw.im/rtfd/cmd.commitID={{.Commit}}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm64
archives:
  - id: foo
    name_template: >-
      {{- .Binary }}.
      {{- .Version }}.
      {{- title .Os }}.
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README*.md'
      - 'NOTICE'
      - '.github'
