language: python
sudo: enabled
env:
- CODECOV_TOKEN="c2ffcd3e-19f7-4df6-9ec8-8e61b9757366"
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- nightly
- pypy
- pypy3
matrix:
  allow_failures:
  - python: nightly
before_install:
- sudo apt-get update
- sudo apt-get install nginx
install:
- pip install codecov
- make dev
script:
- coverage run setup.py test
after_success:
- codecov
deploy:
  provider: pypi
  user: saintic
  password:
    secure: dCaNIvmEvT/c+3mGjGlrAYoNcB3e3S9ykKgK+HaYyEyWjVLpYa3WFA7YGle32QGDCCRIWr39xHVl7jFQVrVzxZqaBi6h/Sxrn3qhidSIg+MPP/5oJ1BLRnF9UnGzlWIXjqdA5sA7y7geXrDV52B0nkoaV711aCcuhtPulSZYQEi/o8MkGKq6bJ0eXoJeMhS28J0gCNN0yGKEC9Sdr3xs06WPyaFm/Ir/jw1IUWJKoSQsl+HkU68An/iivFK+2GrzXZGjKDVycHl6VsdyiFPCB7DzpYrFbKMZ7OcnbeU18LkMsyAqTkK7ZaIMt+8W2xtOinrl7DqShRT/lImvQVF6C4/Dwsw/Uqt44/V6ewwLhdhZ4LrfHoW9AoxGFk0g6faAsl98VItX+iXV3igqdh3HBHrda8otuurNmO0slH2pHFGsANEnc6iHvLEO3p0zOMFUJRVZ8H6ZZ4BW7sKDVHxOcV/qkp5RHbvUB58EgP8RvpFZtX+z0hvVG2r8NHR3nkwQL3c58b3KpWBQKDAX7V6NdkJiAsFSJSdgw/6+invHUkamYlivtARdP6j7CxwxZvH5WV123c6KhPM6wYTQnJDRyw9GUWd8t+X0ziv3I+sRTxyDgLDLMiSpi4btNNIAA+QG3SHWqKKHV+wXLw1oL0WEfjAbwAqw7iQqwKyVF6O4DUI=
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    python: 2.7
    tags: true
    branch: master
